### ISSUE TITLE
Build Error on iOS with Linker

### ISSUE THREAD

**Issue by dansiegel** [TheEightBot/Aurora-Support#1]
**Description**

When setting the Linker Behavior to Link All on iOS, the build will fail with the following error:

MTOUCH : error MT2101: Can't resolve the reference 'System.Boolean System.String::Contains(System.Char)', referenced from the method 'System.Void Aurora.iOS.Renderers.NumericDecimalEntryRenderer::SetEditingValue()' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.

Note that this seems to be limited to Link All only. When I tried Link SDK Only I ended up with a different issue I get to go look at. 

**To Reproduce**

1. Install AuroraControls.Experimental package
1. Set the Linker behavior to Link All
1. Build

**Expected behavior**

No issues building with the Linker on

**Additional context**

The app I'm using currently has the latest stable releases of:

- Prism.DryIoc.Forms
- ReactiveUI
- Xamarin.Forms (3.6.0.293080)
- Syncfusion.DataGrid
- Syncfusion.PdfViewer
- Xamarin.FFImageLoading.Svg.Forms

Hit me up on Slack if you need the full build log from Azure Pipelines

**Comment by michaelstonis** [comment]
Can you provide a sample project or info on which version on Xamarin was used to compile by chance? We ran through what should be a similar setup, but we didn't hit this linker issue.

**Comment by michaelstonis** [comment]
I think we finally tracked this one down. It looks like it is related to DevOps. It has to do with the older default version of Xamarin that is running by default. The way to get it to update to a newer version is to change the environment using the following technique: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#how-can-i-manually-select-versions-of-tools-on-the-hosted-macos-agent

<img width="1205" alt="Azure DevOps Services" src="https://user-images.githubusercontent.com/120685/59768009-26b30a80-9269-11e9-8827-f9eaf9764cb3.png">
