### ISSUE TITLE
I would like to use Font Awesome in the Image Button Control ?

### ISSUE THREAD

**Issue by stephenhauck** [TheEightBot/Aurora-Support#3]
I was wondering if it's possible to use Font Awesome in the Image Button Control so I don't have to add SVG files to the app ?

**Comment by michaelstonis** [comment]
I don't think that we can get that directly to work today, but it does look like there is decent support for Font Awesome with SkiaSharp. We will definitely look into what we can do to support some of this functionality.

In the meantime, it looks like you can export the fonts as SVGs from the font awesome website. It does mean you would still have to embed these in the app, but it provides a way to use them for now.

![image](https://user-images.githubusercontent.com/120685/61794741-6e3c3180-ade7-11e9-93bc-71c72ffbd179.png)

**Comment by stephenhauck** [comment]
Thanks for the response, I look forward to any updates or changes that make life easier ;)

**Comment by michaelstonis** [comment]
Font awesome support has been added to the library. Pretty much all text displaying controls now offer support for custom icon fonts. For more information, please see the [IsIconifiedText](https://docs.auroracontrols.app/controls/isiconifiedtext/) documentation.
