### ISSUE TITLE
Text / Font Awesome on gradient circular button or shape image button ?

### ISSUE THREAD

**Issue by stephenhauck** [TheEightBot/Aurora-Support#4]
As the title says, would love to be able to have text / Font Awesome label on gradient circular button or allow the image button to be shaped like square, rect, round ?

**Comment by michaelstonis** [comment]
All good feedback. I am looking into how we can make font awesome integration better. Controlling the shape of the image button should be no big deal. We can get that rolled in!

**Comment by idSoftwareStephenH** [comment]
I haven't seen any email on updates or anything .. did I miss them ?

**Comment by michaelstonis** [comment]
We have these changes ready to go in an internal release, but they just need a little more testing. We should have these ready to go for our next release soon!

**Comment by michaelstonis** [comment]
We've updated the circular gradient button to allow a square, rounded square and circular background. Additionally, we added support for displaying fonts to the control as well.
