### ISSUE TITLE
registration issue

### ISSUE THREAD

**Issue by LivingMachine00** [TheEightBot/Aurora-Support#5]
good evening

I inserted my email and orderID  = #

after that, I inserted bundle name from VS as indicated in your tutorial.

no serial key generated

**Comment by michaelstonis** [comment]
Howdy,

Can you post your order id? We can take a look into what may have happened with your registration.

**Comment by LivingMachine00** [comment]
ORDER ID
order id = #7ZQQOCLJ





[1490973424822_PastedImage]
Luciano Paoli

luciano_paoli@hotmail.com

luciopaoli.altervista.org<http://luciopaoli.altervista.org>




________________________________
Da: Michael Stonis <notifications@github.com>
Inviato: mercoledì 21 agosto 2019 05:17
A: TheEightBot/Aurora-Support <Aurora-Support@noreply.github.com>
Cc: LivingMachine00 <luciano_paoli@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [TheEightBot/Aurora-Support] registration issue (#5)


Howdy,

Can you post your serial key? We can take a look into what may have happened with your registration.
